### PR TITLE
Added page heading in create connector

### PR DESCRIPTION
**Pull request by indraraj**
- Added the page heading to create connector page.

### CODE REVIEW

**Review by uidoyen — COMMENTED** [review]
@indraraj any particular reason to replace SASS with CSS?

**Comment by indraraj** [comment]
> @indraraj any particular reason to replace SASS with CSS?

Honestly no such particular reason it's just that I have been working with CSS lately. BTW I am totally in for using SCSS it would be nice.

**Comment by indraraj** [comment]
rebased to latest master, reverted to use the SCSS. 

@uidoyen @mdrillin I was thinking since we want to use SCSS we should then phase out the CSS and use SCSS uniformly across the app and configure the proper loader to handle the SCSS files. WDYT?

**Comment by uidoyen** [comment]
@in

> rebased to latest master, reverted to use the SCSS.
> 
> @uidoyen @mdrillin I was thinking since we want to use SCSS we should then phase out the CSS and use SCSS uniformly across the app and configure the proper loader to handle the SCSS files. WDYT?

I think you are right. Let's merge this and then we can continue.

**Review by uidoyen — APPROVED** [review]

**Comment by uidoyen** [comment]
> @in
> 
> > rebased to latest master, reverted to use the SCSS.
> > @uidoyen @mdrillin I was thinking since we want to use SCSS we should then phase out the CSS and use SCSS uniformly across the app and configure the proper loader to handle the SCSS files. WDYT?
> 
> I think you are right. Let's merge this and then we can continue.

PostCSS loader is already configured and SCSS is working fine.

**Comment by indraraj** [comment]
> > @in
> > > rebased to latest master, reverted to use the SCSS.
> > > @uidoyen @mdrillin I was thinking since we want to use SCSS we should then phase out the CSS and use SCSS uniformly across the app and configure the proper loader to handle the SCSS files. WDYT?
> > 
> > 
> > I think you are right. Let's merge this and then we can continue.
> 
> PostCSS loader is already configured and SCSS is working fine.

it would be better if we could use .scss file also

**Pull request merged**
