### PR TITLE
Updating the validate & next button position as per UX feedback

### PR DESCRIPTION
**Pull request by indraraj**
- Updated the validate & next button position as per UX feedback

### CODE REVIEW

**Review by mdrillin — CHANGES_REQUESTED** [review]
The positioning of the buttons looks fine.   However, the enablement of 'Skip to finish' I think needs to be addressed.  Skip to finish should be disabled if the current page is incomplete or invalid. (I think it can use the same enablement logic as the 'Next' button).

**Comment by indraraj** [comment]
> The positioning of the buttons looks fine. However, the enablement of 'Skip to finish' I think needs to be addressed. Skip to finish should be disabled if the current page is incomplete or invalid. (I think it can use the same enablement logic as the 'Next' button).

Thanks for pointing, I missed the regression effect on the skip button.

**Comment by indraraj** [comment]
Reverted the `Skip to finish` button as per the current implementation.

**Review by mdrillin — APPROVED** [review]
looks good, thanks

**Pull request merged**
