### PR TITLE
added early finish option and disable filter next for invalid case

### PR DESCRIPTION
**Pull request by indraraj**
- Added option to skip and last 3 steps and early finish.

- Disable the Next and Finish button on the filter page for the invalid scenarios.

- Screenshots.
image
image

### CODE REVIEW

**Comment by uidoyen** [comment]
@indraraj I was thinking if you can show the final floating error message "Creation of the connector failed." at the same place where we are showing the API validation errors to maintain consistency. WDYT?

**Comment by indraraj** [comment]
> @indraraj I was thinking if you can show the final floating error message "Creation of the connector failed." at the same place where we are showing the API validation errors to maintain consistency. WDYT?

my thought the process was that even if the creation of the connector failed used can still move to the next page if validation is true, so we may want to show him this. (As in the above screenshot even the connector creation is failed used can still move to the next page, which implied in the validation msg)

**Comment by indraraj** [comment]
> > @indraraj I was thinking if you can show the final floating error message "Creation of the connector failed." at the same place where we are showing the API validation errors to maintain consistency. WDYT?
> 
> my thought the process was that even if the creation of the connector failed used can still move to the next page if validation is true, so we may want to show him this. (As in the above screenshot even the connector creation is failed used can still move to the next page, which implied in the validation msg)

also if you check on the last page since its the final step I am there removing the validation msg on connector creation fail.

**Comment by uidoyen** [comment]
> > > @indraraj I was thinking if you can show the final floating error message "Creation of the connector failed." at the same place where we are showing the API validation errors to maintain consistency. WDYT?
> > 
> > 
> > my thought the process was that even if the creation of the connector failed used can still move to the next page if validation is true, so we may want to show him this. (As in the above screenshot even the connector creation is failed used can still move to the next page, which implied in the validation msg)
> 
> also if you check on the last page since its the final step I am there removing the validation msg on connector creation fail.

Screenshot from 2020-09-24 16-29-34

This is what I am getting in the last step.

**Comment by indraraj** [comment]
> > > > @indraraj I was thinking if you can show the final floating error message "Creation of the connector failed." at the same place where we are showing the API validation errors to maintain consistency. WDYT?
> > > 
> > > 
> > > my thought the process was that even if the creation of the connector failed used can still move to the next page if validation is true, so we may want to show him this. (As in the above screenshot even the connector creation is failed used can still move to the next page, which implied in the validation msg)
> > 
> > 
> > also if you check on the last page since its the final step I am there removing the validation msg on connector creation fail.
> 
> Screenshot from 2020-09-24 16-29-34
> 
> This is what I am getting in the last step.

this is not the last step its "Data Option" page the last step will be "Runtime Option"

**Comment by uidoyen** [comment]
> > > > > @indraraj I was thinking if you can show the final floating error message "Creation of the connector failed." at the same place where we are showing the API validation errors to maintain consistency. WDYT?
> > > > 
> > > > 
> > > > my thought the process was that even if the creation of the connector failed used can still move to the next page if validation is true, so we may want to show him this. (As in the above screenshot even the connector creation is failed used can still move to the next page, which implied in the validation msg)
> > > 
> > > 
> > > also if you check on the last page since its the final step I am there removing the validation msg on connector creation fail.
> > 
> > 
> > Screenshot from 2020-09-24 16-29-34
> > This is what I am getting in the last step.
> 
> this is not the last step its "Data Option" page the last step will be "Runtime Option"

Yeah, I was bit late to update the comment :smiley:

**Review by uidoyen — APPROVED** [review]
LGTM!

**Pull request merged**
