### PR TITLE
Rework expansion areas in UI

### PR DESCRIPTION
**Pull request by mdrillin**
Replaced the accordion usages on the form pages with ExpansionSection - seems more appropriate according to patternfly examples.
- renamed ConfigureConnectorTypeComponent to ConfigureConnectorComponent
- replaced accordion usages with ExpansionSection
- indent form inputs to better distinguish the different sections.  Each area is titled, with exansion section below it.

example screenshots 
### Properties Step:
-----------------------------------------------------------------------------------------
ConnectionProperties

### Data Options Step:
-----------------------------------------------------------------------------------------
DataOptions

### Runtime Options Step:
-----------------------------------------------------------------------------------------
RuntimeOptions

### CODE REVIEW

**Comment by uidoyen** [comment]
I think handling expansion with the title itself would be more generic then adding a separate expansion area. Expansion section looks different then actual UX. Maybe we can discuss with UX team.

**Review by uidoyen — COMMENTED** [review]
I think handling expansion with the title itself would be more generic then adding a separate expansion area. Expansion section looks different then actual UX. Maybe we can discuss with UX team.

**Review by indraraj — APPROVED** [review]
Margin it now, improvement looks good. We can run the changes with UX later and can update if needed.

**Comment by mdrillin** [comment]
@uidoyen agree, UX may have some input on this - we can adjust if needed after their review.  It may be better to just remove the titles and use the expansion text as the title.

**Pull request merged**
